### ISSUE TITLE
Wrong example in Readme

### ISSUE THREAD

**Issue by marcolink** [ladariha/junitxml-to-javascript#8]
Hi,

first of all, thanks for this great project, it's exactly what I need 👍 

While playing around, I figured out that the `modifier` example might be wrong.

it says:
```js
 const Parser = require("junitxml-to-javascript");
     const p = new Parser({modifier : (xmlObject) => {
         const x = {};
         x.testsuites = xmlObject;
         return x;
     });
``` 

but I think it should be:
```js
 const Parser = require("junitxml-to-javascript");
     const p = new Parser({modifier : (xmlObject) => {
         const x = {};
         x.testsuites = xmlObject.testsuites;
         return x;
     });
```

**Comment by ladariha** [comment]
thanks for noticing, good catch :) I'll fix it

**Comment by ladariha** [comment]
Better late than never I hope :) Fixed in https://github.com/ladariha/junitxml-to-javascript/commit/b12f5ccd9b604118f5dd7381cfa3ed3a13de3042
